variables:
  DOCKER_REGISTRY: 180430814937.dkr.ecr.us-east-1.amazonaws.com
  APP_NAME: everclone
  DOCKER_HOST: tcp://docker:2375
  AWS_DEFAULT_REGION: us-east-1

publish: 
  image: 
    name: amazon/aws-cli # sign into ecr
    entrypoint: [""]
  services:
    - docker:dind #
  before_script:
    - amazon-linux-extras install docker
    - curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose

  script:
    # - docker build -t $DOCKER_REGISTRY/APP_NAME:$CI_PIPELINE_IID .
    # - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 180430814937.dkr.ecr.us-east-1.amazonaws.com
    # - docker push $DOCKER_REGISTRY/APP_NAME:$CI_PIPELINE_IID
    - echo "HI"
