apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
      - name: reggie
      containers:
      - name: everclone-server
        imagePullPolicy: Always
        image: 180430814937.dkr.ecr.us-east-1.amazonaws.com/docker_images:project_server
        ports:
          - containerPort: 7000
            protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"