apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: everclone-client
        imagePullPolicy: IfNotPresent
        image: 180430814937.dkr.ecr.us-east-1.amazonaws.com/docker_images:project_server
        ports:
          - containerPort: 7000
            protocol: TCP