
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JeffDegoma/argocd.git
    targetRevision: HEAD
    path: example-app
    directory:
      recurse: true
  destination:
    server: https://20A25F3CF983336B748831C35D0620BB.gr7.us-east-1.eks.amazonaws.com
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
